config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  root to: 'posts#index'
  get "/users/:id/like" => "users#like"
  resources :users, only: [:index, :show]
  get '/posts/liked' => 'posts#rank'
  get '/posts/search' => 'posts#search' #ボタンの検索
  post "/posts/:id/button" => "posts#button"
  resources :posts do
    resources :likes, only: [:create, :destroy]
  end
  get "/terms" => "home#terms"
  get "/privacy" => "home#privacy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  def like
    return Like.find_by(post_id: self.id)
  end
end

app/models/like.rb
class Like < ApplicationRecord
    belongs_to :post
    belongs_to :user

    validates :post_id, uniqueness: { scope: :user_id } #１ユーザーが１ボタンに１いいね
end

app/models/post.rb
class Post < ApplicationRecord

    belongs_to :user
    has_many :likes, dependent: :destroy
    has_one_attached :audio

    validates :title, {presence: true, length: { maximum: 20 }} #投稿のコンテンツにバリデーション
    validates :audio, {presence: true}
    validate :audio_type, :audio_size

    def user
        return User.find_by(id: self.user_id)
    end

    def self.search(keyword)
        where(["title like?", "%#{keyword}%"])
    end

    def audio_type
        if audio.blob
            if !audio.blob.content_type.in?(%('audio/mpeg audio/mp4 audio/x-wav'))
                errors.add(:audio, 'はmp3、wav、m4a形式でアップロードしてください')
            end
        else

        end
    end

    def audio_size
        if audio.blob
            if audio.blob.byte_size > 5.megabytes
                errors.add(:audio, "ファイルを5MB以内にしてください")
            end
        end
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy

  def already_liked?(post)
    self.likes.exists?(post_id: post.id)
  end

  def post
    return Post.find_by(post_id: self.post_id)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    def authenticate_user #ユーザーがログインしてない時の処理
        if current_user == nil
            flash[:notice] = "ログインが必要です"
            redirect_to new_user_session_path
        end
    end

    def forbid_login_user #ユーザーがログインしてる時の処理
        if current_user
            flash[:notice] = "すでにログインしています"
            redirect_to posts_path
        end
    end

    private

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
        devise_parameter_sanitizer.permit(:account_update, keys: [:username])
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def terms
   
  end

  def privacy

  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    before_action :authenticate_user, {only: [:create, :destroy]}
  
    def create
        @like = current_user.likes.create(post_id: params[:post_id])
        @post = Post.find_by(id: params[:post_id])
    end

    def destroy
        @like = Like.find_by(post_id: params[:post_id], user_id: current_user.id)
        @like.destroy
        @post = Post.find_by(id: params[:post_id])
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :authenticate_user, {only: [:new, :create]} #ログインしていないと新規投稿できない
  before_action :ensure_correct_user, {only: [:edit, :update, :destroy]} #本人しか編集、削除ができない
  before_action :publishing_settings, {only: [:show]} #非公開の投稿は本人しかアクセスできない

  def ensure_correct_user #投稿者本人かどうかのチェック
    @post = Post.find_by(id: params[:id])
    if current_user
      if @post.user_id == current_user.id || current_user.admin
      else
        flash[:notice] = "権限がありません"
        redirect_to post_path(@post)
      end
    else
      flash[:notice] = "権限がありません"
      redirect_to post_path(@post)
    end
  end

  def publishing_settings
    @post = Post.find_by(id: params[:id])
    if @post.status == 0 #公開
    elsif @post.status == 1 #限定公開
    elsif @post.status == 2 #非公開
      if current_user
        if @post.user_id == current_user.id || current_usr.admin
        else
          flash[:notice] = "ボタンが非公開です"
          redirect_to posts_path
        end
      end
    end
  end

  def search
    @posts = Post.search(params[:keyword]).limit(20)
    @keyword = params[:keyword]
  end

  def index
    @posts = Post.where(status: 0).order(created_at: :desc).page(params[:page]).per(20)
  end

  def rank
    @post_like_ranks = Post.find(Like.group(:post_id).order('count(post_id) desc').limit(20).pluck(:post_id))
  end

  def show
    @post = Post.find_by(id: params[:id])
    @post_like_ranks = Post.find(Like.group(:post_id).order('count(post_id) desc').limit(10).pluck(:post_id))
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.create(post_params)
    if @post.save
      redirect_to posts_path, notice: "投稿を作成しました"
    else
      render :new
    end
  end

  def edit
    @post = Post.find_by(id: params[:id])
  end

  def update
    if @post.update(post_params)
      redirect_to root_path, notice: "投稿を更新しました"
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find_by(id: params[:id])
    @post.destroy
    redirect_to posts_path, notice: "投稿を削除しました"
  end

  private
  def post_params
    params.require(:post).permit(:title, :audio, :status).merge(user_id: current_user.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :admin_user, {only: [:index]}
  before_action :ensure_correct_user, {only: [:like]}

  def admin_user
    if current_user.admin
    else
        flash[:notice] = "権限がありません"
        redirect_to posts_path
    end
  end

  def ensure_correct_user #投稿者本人かどうかのチェック
    @user = User.find_by(id: params[:id])
    if current_user
      if @user.id == current_user.id || current_user.admin
      else
        flash[:notice] = "権限がありません"
        redirect_to posts_path
      end
    else
      flash[:notice] = "権限がありません"
      redirect_to posts_path
    end
  end

  def index
    @users = User.all.order(created_at: :desc)
  end

  def show
    @user = User.find_by(id: params[:id])
    @posts = Post.where(user_id: @user.id).order(created_at: :desc).page(params[:page]).per(20)
    @post_liked = Like.where(user_id: @user.id)
    @user_posts = @user.posts #ユーザーの投稿を取得
    @likes_count = 0
    @user_posts.each do |post|
      @likes_count += post.likes.count
    end
  end

  def like
    @user = User.find_by(id: params[:id])
    @posts = Post.where(user_id: @user.id).order(created_at: :desc)
    @post_liked = Like.where(user_id: @user.id)
    @likes = Like.where(user_id: @user.id).order(created_at: :desc).page(params[:page]).per(20)
    @user_posts = @user.posts #ユーザーの投稿を取得
    @likes_count = 0
    @user_posts.each do |post|
      @likes_count += post.likes.count
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/_ad.html.erb
<!-- 横長 -->
<div class="container">
    <div class="ad-sm">
        <!-- admax -->
        <script src="https://adm.shinobi.jp/s/0aeda80c3473407d83ddfb6b95f56a72"></script>
        <!-- admax -->
    </div>
    <div class="ad-pc">
        <!-- admax -->
        <script src="https://adm.shinobi.jp/s/e52e263ba4089ac7dda7ea6422e88edc"></script>
        <!-- admax -->
    </div>
</div>

app/views/home/_ad2.html.erb
<div class="container">
    <div class="ad-sm my-3">
        <!-- admax -->
        <script src="https://adm.shinobi.jp/s/a29b75be017e3580047737d3e1852c50"></script>
        <!-- admax -->
    </div>
    <div class="ad-pc my-3">
        <!-- admax -->
        <script src="https://adm.shinobi.jp/s/fff89724b8d5585041d2d8792986b837"></script>
        <!-- admax -->
        <!-- admax -->
        <script src="https://adm.shinobi.jp/s/86d55640ddcfe48c64c5e3db03c8f2a2"></script>
        <!-- admax -->
    </div>
</div>

app/views/home/_header_link.html.erb
<div class="header-link my-1">
    <%= link_to "ボタン一覧", posts_path %>
    <%= link_to "ボタンを作成", new_post_path %>
    <%= link_to "音声リセット", request.url %>
</div>

app/views/home/about.html.erb
<% content_for(:html_title) { 'このサイトの使い方' } %>
<div class="container">
    <h3>ボタンリストの使いかた</h3>
    ボタンリストは音声が鳴るボタンを作成して共有できるサイトです。
    効果音を鳴らしたいとき、暇なときにお使いください。
    <h4>ボタンの作成方法</h4>
    ※ボタンの作成にはユーザー登録が必要です
    <h4>いいね機能</h4>
    ログイン状態でボタン下のハートマークを押すと後から確認することができます。
    <h4>ボタンの公開設定について</h4>
    ボタン作成、編集画面からボタンの公開設定をすることができます。
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>
      <%= content_for?(:html_title) ? yield(:html_title) : "" %> ｜ボタンリスト
    </title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/16d5680429.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.0/jquery.min.js"></script>
    <link href="https://fonts.googleapis.com/earlyaccess/nicomoji.css" rel="stylesheet">
    <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-7770438803533980" crossorigin="anonymous"></script>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-91XKPHSGTP"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());
      gtag('config', 'G-91XKPHSGTP');
    </script>
  </head>

  <body>
    <header>
      <div class="container">
        <div class="header-left">
          <%= link_to posts_path do %>
            <%= image_tag "header-logo", class: "header-logo "%>
          <% end %>
          <%= link_to "ボタンリスト", posts_path, class: "header-title" %>
        </div>
        <div class="header-right">
          <% if user_signed_in? %>
            <%= link_to "マイページ", user_path(current_user) %>
            <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "btn btn-primary" %>
          <% else %>
            <%= link_to "ログイン", new_user_session_path, class: "btn btn-primary" %>
            <%= link_to "新規登録", new_user_registration_path, class: "btn btn-success" %>
          <% end %>
        </div>
      </div>
    </header>

    <!-- deviseのフラッシュメッセージ -->
    <div class="mx-3">
      <% if flash[:notice] %>
        <p class="alert alert-primary" role="alert"><%= notice %></p>
      <% end %>
      <% if flash[:alert] %>
        <p class="alert alert-danger" role="alert"><%= alert %></p>
      <% end %>
    </div>
    <%= render partial: 'home/header_link' %>

    <%= yield %>

    <footer class="clear">
      <div class="container">
        <div class="footer-left">
        </div>
        <div class="footer-right">
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/likes/_like.html.erb
<% if user_signed_in? %>
    <% if current_user.already_liked?(post) %>
        <%= link_to "/posts/#{post.id}/likes/#{post.like.id}", method: :delete, remote: true do %>
            <i class="fas fa-heart"></i> <%= post.likes.count %>
        <% end %>
    <% else %>
        <%= link_to post_likes_path(post), method: :post, remote: true do %>
            <i class="far fa-heart"></i> <%= post.likes.count %>
        <% end %>
    <% end %>
<% else %>
<%= link_to new_user_session_path do %>
    <i class="far fa-heart"></i> <%= post.likes.count %>
<% end %>
<% end %>

app/views/likes/create.js.erb
$('#like_buttons_<%= @post.id %>').html("<%= j(render partial: 'likes/like', locals: {post: @post}) %>");

app/views/likes/destroy.js.erb
$('#like_buttons_<%= @post.id %>').html("<%= j(render partial: 'likes/like', locals: {post: @post}) %>");

app/views/posts/_error_form.html.erb
<!-- エラーメッセージの共通化 -->
<% if post.errors.any? %>
    <% post.errors.full_messages.each do |message| %> <!-- バリデーションのエラーメッセージ -->
        <div class="alert alert-danger" role="alert">
            <%= message %>
        </div>
    <% end %>
<% end %>

app/views/posts/edit.html.erb
<% content_for(:html_title) { '投稿を編集' } %>
<div class="container">
    <h3>ボタンを編集</h3>
    <!-- エラーメッセージ -->
    <%= render partial: 'error_form', locals: { post: @post } %>
    <!-- 新規投稿フォーム -->
    <%= render partial: 'new_post_form', locals: { post: @post } %>
</div>

app/views/posts/show.html.erb
<% content_for(:html_title) { '#{@post.title}' } %>
<div class= "container" %>
    <h3>ボタン詳細</h3>
    <div class="post-show my-2">
        <% if @post.status == 0 %>
        <% elsif @post.status == 1 %>
            設定：限定公開
        <% elsif @post.status == 2 %>
            設定：非公開
        <% end %>
        <p><%= @post.title %> <%= File.extname(url_for(@post.audio)).downcase %></p>
        <div class="post-show-post mx-auto">
            <button ontouchstart="" data-id=<%= @post.id %>><%= @post.title.truncate(13) %></button>
            <%= audio_tag(url_for(@post.audio), id: "play-button-#{@post.id}", preload: "metadata", controlslist: "nodownload") %>
        </div>
        <div class="like_buttons", id="like_buttons_<%= @post.id %>">
            <%= render partial: 'likes/like', locals: { post: @post } %>
        </div>
        <br>
        <%= @post.created_at.strftime("%Y-%m-%d %H:%M") %>
        <div class="shere_button my-1">
            <%= link_to "https://twitter.com/share?url=#{request.url}&text=「#{ @post.title}」ボタンを押してみよう！&hashtags=ボタンリスト", rel: "noopener noreferrer", target: '_blank' do %>
                <i class="fa-brands fa-twitter-square fa-3x", style='color: #3399FF;'></i>
            <% end %>
            <%= link_to "https://www.facebook.com/share.php?u=#{request.url}", rel: "noopener noreferrer", target: "_blank" do %>
                <i class="fa-brands fa-facebook-square fa-3x", style='color: #1877f2;'></i>
            <% end %>
            <%= link_to "https://line.me/R/msg/text/?#{request.url}", rel: "noopener noreferrer", target: "_blank" do %>
                <i class="fa-brands fa-line fa-3x", style='color: #06c755;'></i>
            <% end %>
        </div>
        <% if current_user %>
            <% if @post.user_id == current_user.id || current_user.admin %>
                <%= link_to "編集", edit_post_path(@post) %>
                <%= link_to "削除", post_path(@post), method: :delete, data: {confirm: "投稿を削除しますか？"} %>
            <% end %>
            <% if current_user.admin %>
                <p>ユーザ：<%= link_to @post.user.username, user_path(@post.user) %></p>
                <p>公開設定：<%= @post.status %>
            <% end %>
        <% end %>
    </div>
    <h5 class="clear">人気のボタン</h5>
    <% @post_like_ranks.each do |post| %>
        <div class="post">
            <% if post.status == 0 %>
                <button ontouchstart="" data-id=<%= post.id %>><%= post.title.truncate(13) %></button>
                <%= audio_tag(url_for(post.audio), id: "play-button-#{post.id}", preload: "metadata", controlslist: "nodownload") %>
                <br>
                <div class="like_buttons", id="like_buttons_<%= post.id %>">
                    <%= render partial: 'likes/like', locals: { post: post } %>
                </div>
                <%= link_to "詳細", post_path(post) %>
            <% end %>
        </div>
    <% end %> 
</div>

app/views/users/index.html.erb
<% content_for(:html_title) { 'ユーザ一覧' } %>
<div class="container">
<h1>Users</h1>
<table class="table table-hover">
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Address</th>
      <th colspan="3"></th>
    </tr>
    <% @users.each do |user| %>
      <tr>
        <td scope="row"><%= user.username %></td>
        <td scope="row"><%= user.email %></td>
        <td><%= link_to '詳細', user_path(user), class: "btn btn-outline-primary btn-sm" %></td>
        <% if current_user %>
            <% if current_user == user || current_user.admin %>
                <td><%= link_to '編集', edit_user_registration_path(user), class: "btn btn-outline-primary btn-sm" %></td>
                <td><%= link_to '削除', user_registration_path(user), class: "btn btn-outline-danger btn-sm", method: :delete, data: { confirm: 'アカウントを削除しますか？？' } %></td>
            <% end %>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to '新規登録', new_user_registration_path, class: 'btn btn-primary btn-sm' %>
</div>

app/views/users/like.html.erb
<% content_for(:html_title) { 'いいねした投稿' } %>
<div class="container">
    <h3>ユーザー詳細</h3>
    <p><%= @user.username %></p>
    <% if current_user %>
        <% if @user == current_user %>
            <p><%= @user.email %></p>
        <% end %>
    <% end %>
    <p>投稿数：<%= @posts.count %></p>
    <p>いいねされた数：<%= @likes_count %></p>
    <h5><%= link_to "投稿したボタン", user_path(@user) %>　<%= link_to "お気に入り", "/users/#{@user.id}/like" %></h5>
    <div class="posts">
        <% @likes.each do |like| %>
            <div class="post">
                <% if like.post.status == 0 %>
                    <button ontouchstart="" data-id=<%= like.post.id %>><%= like.post.title.truncate(13) %></button>
                    <%= audio_tag(url_for(like.post.audio), id: "play-button-#{like.post.id}", preload: "metadata", controlslist: "nodownload") %>
                    <br>
                    <div class="like_buttons", id="like_buttons_<%= like.post.id %>">
                        <%= render partial: 'likes/like', locals: { post: like.post } %>
                    </div>
                    <%= link_to "詳細", post_path(like.post) %>
                <% elsif like.post.status == 1 %>
                    <% if current_user %>
                        <% if like.post.user_id == current_user.id || current_user.admin %>
                            <button ontouchstart="" data-id=<%= like.post.id %>><%= like.post.title.truncate(13) %></button>
                            <%= audio_tag(url_for(like.post.audio), id: "play-button-#{like.post.id}", preload: "metadata", controlslist: "nodownload") %>
                            <br>
                            <div class="like_buttons", id="like_buttons_<%= like.post.id %>">
                                <%= render partial: 'likes/like', locals: { post: like.post } %>
                            </div>
                            <%= link_to "詳細", post_path(like.post) %>
                        <% end %>
                    <% end %>
                <% elsif like.post.status == 2 %>
                    <% if current_user %>
                        <% if like.post.user_id == current_user.id || current_user.admin %>
                            <button ontouchstart="" data-id=<%= like.post.id %>><%= like.post.title.truncate(13) %></button>
                            <%= audio_tag(url_for(like.post.audio), id: "play-button-#{like.post.id}", preload: "metadata", controlslist: "nodownload") %>
                            <br>
                            <div class="like_buttons", id="like_buttons_<%= like.post.id %>">
                                <%= render partial: 'likes/like', locals: { post: like.post } %>
                            </div>
                            <%= link_to "詳細", post_path(like.post) %>
                        <% end %>
                    <% end %>
                <% end %>
            </div>
        <% end %> 
    </div>
    <div class="clear">
        <%= paginate @likes %>
    </div>
</div>

app/views/users/show.html.erb
<% content_for(:html_title) { '投稿したボタン' } %>
<div class="container">
    <h3>ユーザー詳細</h3>
    <p><%= @user.username %></p>
    <% if current_user %>
        <% if @user == current_user || current_user.admin %>
            <p><%= @user.email %></p>
            <%= link_to '編集', edit_user_registration_path(@user), class: "btn btn-outline-primary btn-sm" %>
        <% end %>
        <% if current_user.admin %>
            <p class="my-2">権限：<%= @user.admin %></p>
        <% end %>
    <% end %>
    <p class="mt-3">投稿数：<%= @posts.count %></p>
    <p>いいねされた数：<%= @likes_count %></p>
    <h5><%= link_to "投稿したボタン", user_path(@user) %>　<%= link_to "お気に入り", "/users/#{@user.id}/like" %></h5>
    <div class="posts">
        <% @posts.each do |post| %>
            <div class="post">
                <button ontouchstart="" data-id=<%= post.id %>><%= post.title.truncate(13) %></button>
                <%= audio_tag(url_for(post.audio), id: "play-button-#{post.id}", preload: "metadata", controlslist: "nodownload") %>
                <br>
                <div class="like_buttons", id="like_buttons_<%= post.id %>">
                    <%= render partial: 'likes/like', locals: { post: post } %>
                </div>
                <%= link_to "詳細", post_path(post) %>
            </div>
        <% end %> 
    </div>
    <div class="clear">
        <%= paginate @posts %>
    </div>
</div>